language: c
sudo: false

matrix:
  include:
    - os: osx
      addons:
        homebrew:
          update: false
          packages:
            - gcc
            - cmake
            - openmpi
      before_install:
        - brew install gcc
        - brew link gcc
        - brew install openmpi
        - brew link openmpi
      script:
        - cmake --version
        - ./install.sh --lang "C C++ Fortran" --build release --lib dynamic --mem heap --par none -s gnu
