language: c
sudo: required

git:
  submodules: false
  symlinks: true
  clone: true
  #quiet: true

##############################

# blocklist
branches:
  except:
  - development

# safelist
branches:
  only:
  - master

os:
  - linux
  #- osx

#jobs:
#  allow_failures:
#    - os: osx

addons:
  #homebrew:
  #  packages:
  #    - gcc
  #    - cmake
  #    - openmpi
  #  update: true
  apt:
    packages:
      - gcc
      - cmake-3.16
      - mpich
      - gfortran

##############################

cache:
  apt: true
  pip: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.local

matrix:
  include:
    - os: linux
      dist: trusty
      addons:
        apt:
          sources:
            - kalakris-cmake
            - ubuntu-toolchain-r-test
          packages:
            - cmake-3.16
            - gcc-9
            - gfortran-9
      env:
        - GFORTRAN=gfortran-9
        - gfortran=gfortran-9
        - GCOV=gcov-9

##############################

install:
  - pwd
  - cmake --version
  - ./install.sh --lang "C C++ Fortran" --build release --lib dynamic --mem heap --par none

script: ./install.sh --lang "C C++ Fortran" --build release --lib dynamic --mem heap --par none --dryrun

#after_success:
#  - bash <(curl -s https://codecov.io/bash)