language: c
sudo: required

git:
  submodules: false
  symlinks: true
  clone: true
  #quiet: true

##############################

# blocklist
branches:
  except:
  - development

# safelist
branches:
  only:
  - master

##############################

matrix:
  fast_finish: true
  include:
    - &macOS
      os: osx
      osx_image: xcode10.2
      addons:
        homebrew:
          packages:
            - gcc
            - cmake
            - openmpi
          update: true
    - &macOS_allowed_failure
      <<: *macOS
      addons:
        homebrew:
          packages:
            - gcc
            - cmake
            - openmpi
          update: true
    - &ubuntu
      os: linux
      sudo: false
      dist: xenial
      env:
        - GCC=9
      cache:
        apt: true
        directories:
          - "$CACHE"
      addons:
        apt:
          sources: &linuxsrcs
            - ubuntu-toolchain-r-test
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
              key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
          packages: &gcc8pkgs
            - cmake
            - gcc-9
            - g++-9
            - gfortran-9
    -
      <<: *ubuntu
      env:
        - GCC=9
      addons:
        apt:
          sources: *linuxsrcs
          packages: &gcc7pkgs
            - cmake
            - gcc-9
            - g++-9
            - gfortran-9
    -
      <<: *ubuntu
      addons:
        apt:
          sources: *linuxsrcs
          packages:
            - gcc-8
            - g++-8
            - gfortran-8
    - &linux_allowed_failure
      <<: *ubuntu
      addons:
        apt:
          sources: *linuxsrcs
          packages: *gcc8pkgs

  allow_failures:
    - *linux_allowed_failure
    - *macOS_allowed_failure

##############################

install:
  - pwd
  - ./install.sh --lang "C C++ Fortran" --build release --lib dynamic --mem heap --par none --yes-to-all 

#after_success:
#  - bash <(curl -s https://codecov.io/bash)