language: c
sudo: required

git:
  submodules: false
  symlinks: true
  clone: true
  #quiet: true

##############################

# blocklist
branches:
  except:
  - development

# safelist
branches:
  only:
  - master

os:
  - linux
  - osx

#jobs:
#  allow_failures:
#    - os: osx

addons:
  homebrew:
    packages:
      - gcc
      - cmake
      - openmpi
    update: true
  apt:
    packages:
      - gcc
      - cmake
      - mpich
      - gfortran

##############################

jobs:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode10.2

##############################

install:
  - pwd
  - ./install.sh --lang "C C++ Fortran" --build release --lib dynamic --mem heap --par none

#after_success:
#  - bash <(curl -s https://codecov.io/bash)