language: c
sudo: false

before_cache:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew cleanup; fi
# Credit https://discourse.brew.sh/t/best-practice-for-homebrew-on-travis-brew-update-is-5min-to-build-time/5215/9
# Cache only .git files under "/usr/local/Homebrew" so "brew update" does not take 5min every build
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then find /usr/local/Homebrew \! -regex ".+\.git.+" -delete; fi

cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Homebrew

matrix:
  include:

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - mpich
            - gfortran-8
      script:
        - chmod +x ./.travis/install_cmake.sh && ./.travis/install_cmake.sh
        - export FC=gfortran-8
        - cmake --version
        - gfortran-8 --version
        - which mpiexec
        - ./install.sh --lang "C C++ Fortran" --build release --lib dynamic --mem heap --par none -s gnu -f $(which gfortran-8)

    - os: osx
      addons:
        homebrew:
          packages:
          - gcc
          - cmake
          - openmpi
      before_install:
        #- brew install gcc || brew upgrade gcc
        #- brew install cmake || brew upgrade cmake
        #- brew install openmpi || brew upgrade openmpi
        - brew link gcc
        - brew link cmake
        #- brew link openmpi
      script:
        - cmake --version
        - ./install.sh --lang "C C++ Fortran" --build release --lib dynamic --mem heap --par none -s gnu

#    - os: osx
#      script:
#        - wget "https://github.com/cdslaborg/paramonte/releases/download/v1.4.0/libparamonte_c_darwin_x64_gnu_release_dynamic_heap.tar.gz"
#        - tar xvzf libparamonte_c_darwin_x64_gnu_release_dynamic_heap.tar.gz
#        - cd libparamonte_c_darwin_x64_gnu_release_dynamic_heap
#        - ./build.sh
#        - ./run.sh
