language: c
sudo: true

before_cache:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew cleanup; fi
# Credit https://discourse.brew.sh/t/best-practice-for-homebrew-on-travis-brew-update-is-5min-to-build-time/5215/9
# Cache only .git files under "/usr/local/Homebrew" so "brew update" does not take 5min every build
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then find /usr/local/Homebrew \! -regex ".+\.git.+" -delete; fi

cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Homebrew

matrix:
  include:

    - &macOS
      os: osx
      osx_image: xcode10.2
      env:
        - BUILD_TYPE="InstallScript"
          GCC=9
          CC=gcc-9
          CXX=g++-9
          FC=gfortran-9
      addons:
        homebrew:
          packages:
            - gcc
            - mpich
            - shellcheck
          update: true
     #before_install:
        #- brew install gcc || brew upgrade gcc
        #- brew install cmake || brew upgrade cmake
        #- brew install openmpi || brew upgrade openmpi
        #- brew link openmpi
      script:
        - brew link gcc
        - brew link cmake
        - cmake --version
        - ./install.sh --lang "C C++ Fortran" --build release --lib dynamic --mem heap --par "none mpi" #-s gnu

#    - os: linux
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#          packages:
#            - mpich
#            - gfortran-8
#      script:
#        - chmod +x ./.travis/install_cmake.sh && ./.travis/install_cmake.sh
#        - export FC=gfortran-8
#        - cmake --version
#        - gfortran-8 --version
#        - echo >&2 "The MPIEXEC binday path: $(which mpiexec) || echo >&2 "MPI library not found...skipping"
#        - ./install.sh --lang "C C++ Fortran" --build release --lib dynamic --mem heap --par none --fortran $(which gfortran-8) --mpiexec $(which mpiexec) --yes-to-all

#    - name: "darwin"
#      os: osx
#      osx_image: xcode10
#      addons:
#        homebrew:
#          packages:
#            - gcc
#            - cmake
#            - openmpi
#            - update: true
      #before_install:
        #- brew install gcc || brew upgrade gcc
        #- brew install cmake || brew upgrade cmake
        #- brew install openmpi || brew upgrade openmpi
        #- brew link openmpi
#      script:
#        - brew link gcc
#        - brew link cmake
#        - cmake --version
#        - ./install.sh --lang "C C++ Fortran" --build release --lib dynamic --mem heap --par "none mpi" -s gnu

#    - os: osx
#      script:
#        - wget "https://github.com/cdslaborg/paramonte/releases/download/v1.4.0/libparamonte_c_darwin_x64_gnu_release_dynamic_heap.tar.gz"
#        - tar xvzf libparamonte_c_darwin_x64_gnu_release_dynamic_heap.tar.gz
#        - cd libparamonte_c_darwin_x64_gnu_release_dynamic_heap
#        - ./build.sh
#        - ./run.sh
